name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 1433:1433
          - 5000:5000
          - 4200:4200

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./scripts/docker-compose.yml
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/weatherapp:latest

    - name: Deploy to DockerHub
      run: docker-compose -f ./scripts/docker-compose.yml up -d
